version: 2

sources:
  - name: jaffle_shop
    database: PC_DBT_DB
    description: A replica of the postgres database used to power the jaffle_shop app.   
    schema: jaffle_shop
    tables:
      - name: payments

models:
  - name: stg_payments
    config:
      materialized: table
      alias: payment_stg
    columns:
      - name: payment_id
        tests:
          - unique
          - not_null
      - name: payment_method
        tests:
          - accepted_values:
              values: ['credit_card', 'coupon', 'bank_transfer', 'gift_card']
